import '@/styles/reset.css'
import '@/styles/topnav.scss'
import '@/styles/home.scss'
import '@/styles/login.scss'
import '@/styles/transfer.scss'
import '@/styles/disposit.scss'
import '@/styles/balance.scss'
import '@/styles/base.scss'